import { z } from 'zod';
import { asNumber, asString, requiredNumber, requiredString } from '@/lib/schemas/helpers';

export const userCreationSchema = z.object({
  hrmsId: requiredString('HRMS ID is required'),
  username: z.preprocess(asString, z.string().min(3, 'Username must be at least 3 characters')),
  mobileNumber: z.preprocess(
    asString,
    z.string().min(1, 'Mobile number is required').regex(/^[6-9]\d{9}$/, 'Invalid mobile number'),
  ),
  firstName: requiredString('First name is required'),
  lastName: requiredString('Last name is required'),
  address: requiredString('Address is required'),
  dob: z.preprocess(
    asString,
    z.string().min(1, 'Date of birth is required').regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format (YYYY-MM-DD)'),
  ),
  roleId: requiredNumber('Role is required'),
  zoneId: requiredNumber('Zone is required'),
  circleId: requiredNumber('Circle is required'),
  ssaId: requiredNumber('SSA is required'),
  password: z.preprocess(asString, z.string().min(8, 'Password must be at least 8 characters')),
  status: z.preprocess((value) => asNumber(value, -1), z.number().min(0, 'Status is required').max(1, 'Status must be 0 or 1')),
  permissions: z.object({
    dealerPermissions: z.number(),
    walletPermissions: z.number(),
    userPermissions: z.number(),
    commissionPermissions: z.number(),
    plansNumberpermissions: z.number(),
    reportsPermissions: z.number(),
    stockCheck: z.number(),
    dealerMpinReset: z.number(),
    franchiseAddBalance: z.number(),
    bulkRecharge: z.number(),
    varepReports: z.number(),
    userActivityReports: z.number(),
    dealerStatus: z.number(),
    transactionStatus: z.number(),
    topupReversal: z.number(),
    simSaleUpload: z.number(),
    simInventory: z.number(),
    pendingClearence: z.number(),
    inReconsilation: z.number(),
    mobileApp: z.number(),
    deferredCommission: z.number(),
    cbp: z.number(),
    simUpgrade: z.number(),
    mnp: z.number(),
    frcStv: z.number(),
    bulk_purge: z.number(),
    e_auction: z.number(),
    denominations: z.number(),
    prepaidCommissions: z.number(),
    postpaidCommissions: z.number(),
    landlineCommissions: z.number(),
    FOSCreation: z.number(),
  }),
});

export type UserCreationFormData = z.infer<typeof userCreationSchema>;
